/**
 * Generates a single self-contained HTML file for the SDL Interactive Renderer.
 *
 * The output is a zero-dependency* static HTML file that renders all three SDL layers:
 *   layer_platform → service dependency graph
 *   layer_service  → cross-service flow diagrams
 *   layer_logic    → service internals with perspective toggle
 *
 * *Mermaid.js is loaded from jsDelivr CDN for diagram rendering.
 *
 * The client-side JavaScript (CLIENT_JS) is generated by scripts/build.mjs using esbuild,
 * which bundles src/renderer/client/main.ts and all its imports into a minified IIFE.
 */

import type { RenderData } from './reader.js';
import { CLIENT_JS } from './generated/client-bundle.js';

export function generateHtml(data: RenderData, title?: string): string {
  const pageTitle = title ?? deriveTile(data);
  const serialized = JSON.stringify(data);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escHtml(pageTitle)} — SDL Renderer</title>
<script src="https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.min.js"></script>
<style>
${CSS}
</style>
</head>
<body>
<div id="shell">
  <header id="topbar">
    <h1 id="page-title">${escHtml(pageTitle)}</h1>
    <nav id="layer-tabs"></nav>
    <div id="breadcrumb"></div>
  </header>
  <main id="main"></main>
</div>

<script>
const SDL = ${serialized};
${CLIENT_JS}
</script>
</body>
</html>`;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function escHtml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function deriveTile(data: RenderData): string {
  if (data.platforms[0]?.label) return data.platforms[0].label;
  if (data.services[0]?.manifest?.label) return String(data.services[0].manifest.label);
  return 'SDL';
}

// ── Embedded CSS ──────────────────────────────────────────────────────────────

const CSS = `
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
:root {
  --bg: #f8f9fa; --surface: #fff; --border: #e2e8f0; --muted: #64748b;
  --accent: #3b82f6; --accent-dim: #dbeafe; --text: #1e293b;
  --green: #16a34a; --green-dim: #dcfce7;
  --amber: #d97706; --amber-dim: #fef3c7;
  --red: #dc2626; --red-dim: #fee2e2;
  --radius: 8px; --shadow: 0 1px 3px rgba(0,0,0,.08);
}
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  font-size: 14px; line-height: 1.5; color: var(--text); background: var(--bg); }
a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: 'SF Mono', 'Cascadia Code', monospace; font-size: 12px;
  background: var(--border); padding: 1px 5px; border-radius: 3px; }

/* Layout */
#shell { display: flex; flex-direction: column; min-height: 100vh; }
#topbar { background: var(--surface); border-bottom: 1px solid var(--border);
  padding: 0 24px; display: flex; align-items: center; gap: 24px; height: 52px;
  position: sticky; top: 0; z-index: 10; }
#topbar h1 { font-size: 15px; font-weight: 600; }
#layer-tabs { display: flex; gap: 0; }
.tab { padding: 0 16px; height: 52px; display: flex; align-items: center;
  cursor: pointer; border-bottom: 2px solid transparent; color: var(--muted);
  font-size: 13px; font-weight: 500; transition: color .15s; }
.tab:hover { color: var(--text); }
.tab.active { color: var(--accent); border-bottom-color: var(--accent); }
#breadcrumb { font-size: 12px; color: var(--muted); display: flex; align-items: center; gap: 6px; }
.crumb { cursor: pointer; color: var(--accent); }
.crumb:hover { text-decoration: underline; }
#main { flex: 1; padding: 24px; max-width: 1100px; margin: 0 auto; width: 100%; }

/* Cards */
.card { background: var(--surface); border: 1px solid var(--border);
  border-radius: var(--radius); box-shadow: var(--shadow); margin-bottom: 16px; }
.card-header { padding: 14px 18px; border-bottom: 1px solid var(--border);
  display: flex; align-items: center; gap: 10px; }
.card-title { font-weight: 600; font-size: 14px; }
.card-body { padding: 16px 18px; }
.card-body p { color: var(--muted); margin-bottom: 8px; }
.badge { display: inline-block; font-size: 11px; padding: 2px 7px; border-radius: 99px;
  font-weight: 500; }
.badge-blue  { background: var(--accent-dim); color: #1d4ed8; }
.badge-green { background: var(--green-dim); color: #15803d; }
.badge-amber { background: var(--amber-dim); color: #92400e; }
.badge-gray  { background: #f1f5f9; color: #475569; }

/* Grid */
.grid-2 { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 16px; }
.grid-3 { display: grid; grid-template-columns: repeat(auto-fill, minmax(200px, 1fr)); gap: 12px; }

/* Mermaid container */
.mermaid-wrap { border: 1px solid var(--border); border-radius: var(--radius);
  padding: 16px; background: var(--surface); margin-bottom: 20px; overflow-x: auto; }

/* Tables */
table { width: 100%; border-collapse: collapse; font-size: 13px; }
th { text-align: left; padding: 8px 12px; font-weight: 600; border-bottom: 2px solid var(--border);
  color: var(--muted); font-size: 11px; text-transform: uppercase; letter-spacing: .04em; }
td { padding: 8px 12px; border-bottom: 1px solid var(--border); vertical-align: top; }
tr:last-child td { border-bottom: none; }
tr:hover td { background: var(--bg); }

/* Service row */
.svc-row { display: flex; align-items: center; gap: 8px; padding: 12px 16px;
  border-bottom: 1px solid var(--border); cursor: pointer; transition: background .1s; }
.svc-row:hover { background: var(--bg); }
.svc-row:last-child { border-bottom: none; }
.svc-icon { width: 28px; height: 28px; border-radius: 6px; display: flex; align-items: center;
  justify-content: center; font-size: 13px; flex-shrink: 0; }
.svc-icon.backend  { background: #e0e7ff; }
.svc-icon.frontend { background: var(--accent-dim); }
.svc-icon.external { background: var(--amber-dim); }
.svc-icon.worker   { background: var(--green-dim); }
.svc-name { font-weight: 500; flex: 1; }
.svc-domain { color: var(--muted); font-size: 12px; }

/* Steps */
.step { display: flex; gap: 12px; padding: 10px 0; border-bottom: 1px solid var(--border); }
.step:last-child { border-bottom: none; }
.step-id { font-weight: 700; min-width: 28px; color: var(--accent); font-size: 12px; }
.step-arrow { color: var(--muted); font-size: 11px; white-space: nowrap; }
.step-label { flex: 1; }
.step-meta { font-size: 11px; color: var(--muted); }

/* Perspective toggle */
.persp-tabs { display: flex; gap: 0; border: 1px solid var(--border);
  border-radius: 6px; overflow: hidden; margin-bottom: 16px; width: fit-content; }
.persp-tab { padding: 6px 14px; cursor: pointer; font-size: 12px; font-weight: 500;
  color: var(--muted); background: var(--surface); transition: all .15s; }
.persp-tab.active { background: var(--accent); color: #fff; }

/* Rules list */
.rules-list { list-style: none; }
.rules-list li { padding: 5px 0; padding-left: 16px; position: relative; color: var(--text); }
.rules-list li::before { content: '–'; position: absolute; left: 0; color: var(--muted); }

/* Collapse accordion */
details summary { cursor: pointer; list-style: none; padding: 12px 18px;
  display: flex; align-items: center; gap: 8px; }
details summary::before { content: '▶'; font-size: 10px; color: var(--muted);
  transition: transform .15s; }
details[open] summary::before { transform: rotate(90deg); }
details summary::-webkit-details-marker { display: none; }

/* Overview */
#ov-toolbar { display: flex; align-items: center; gap: 6px; padding: 10px 0 12px; flex-wrap: wrap; }
.tog-btn { display: inline-flex; align-items: center; gap: 5px; padding: 5px 12px;
  border: 1px solid var(--border); border-radius: 5px; cursor: pointer;
  font-size: 12px; font-weight: 500; background: var(--surface); color: var(--muted);
  user-select: none; }
.tog-btn.on { background: var(--accent); color: #fff; border-color: var(--accent); }
.tog-btn kbd { background: rgba(0,0,0,.08); border-radius: 3px; padding: 1px 4px;
  font-size: 10px; font-family: inherit; }
.tog-btn.on kbd { background: rgba(255,255,255,.25); }
#ov-body { display: flex; height: calc(100vh - 148px); }
#ov-flows-panel { width: 190px; border: 1px solid var(--border); border-radius: 8px 0 0 8px;
  overflow-y: auto; background: var(--surface); flex-shrink: 0; }
#ov-wrap { flex: 1; border-top: 1px solid var(--border); border-bottom: 1px solid var(--border);
  overflow: hidden; background: #fafbff; cursor: grab; position: relative; transition: opacity .35s; }
#ov-wrap.panning { cursor: grabbing !important; }
#ov-svg { display: block; width: 100%; height: 100%; }
#ov-steps-panel { width: 250px; border: 1px solid var(--border); border-left: none;
  border-radius: 0 8px 8px 0; background: var(--surface); display: flex;
  flex-direction: column; flex-shrink: 0; overflow: hidden; }
#ov-step-list { flex: 1; overflow-y: auto; }
#ov-playback-ctrl { padding: 10px 12px; border-top: 1px solid var(--border); flex-shrink: 0; }
.ov-node { cursor: grab; }
.ov-node.dragging { cursor: grabbing; }
.ov-box { transition: filter .1s; }
.ov-node:hover .ov-box { filter: brightness(.96); }
.ov-flow-item { padding: 8px 12px; cursor: pointer; border-bottom: 1px solid var(--border);
  font-size: 12px; transition: background .1s; }
.ov-flow-item:hover { background: var(--bg); }
.ov-flow-item.active { background: var(--accent-dim); border-left: 3px solid var(--accent); padding-left: 9px; }
.ov-step-item { padding: 6px 10px; border-bottom: 1px solid var(--border); font-size: 11px; }
.ov-step-item.playing { background: var(--accent-dim); }
.ov-node-active .ov-box { filter: drop-shadow(0 0 4px rgba(59,130,246,.7)) brightness(.95); }
#main.ov-full { max-width: none; padding: 24px 12px; }
#ov-tip { position: fixed; pointer-events: none; z-index: 100; background: #1e293b; color: #f8fafc;
  font-size: 11px; padding: 6px 10px; border-radius: 6px; max-width: 220px; line-height: 1.5;
  box-shadow: 0 2px 8px rgba(0,0,0,.25); }
.ov-edge-hit { pointer-events: stroke; }
.ov-macro-node { cursor: pointer; }
.ov-micro-ep  { fill: #e0e7ff; }
.ov-micro-op  { fill: #dcfce7; }
.ov-micro-dep { fill: #fef3c7; }
`.trim();
