import esbuild from 'esbuild';
import { writeFileSync, mkdirSync } from 'fs';
import { execSync } from 'child_process';

// 1. Bundle client code into a self-contained IIFE
const result = await esbuild.build({
  entryPoints: ['src/renderer/client/main.ts'],
  bundle: true,
  format: 'iife',
  minify: true,
  write: false,
  target: ['es2020'],
});

// 2. Write the bundled JS as a generated TS export
const js = result.outputFiles[0].text;
mkdirSync('src/renderer/generated', { recursive: true });
writeFileSync(
  'src/renderer/generated/client-bundle.ts',
  `// AUTO-GENERATED by scripts/build.mjs — do not edit\nexport const CLIENT_JS = ${JSON.stringify(js)};\n`
);

// 3. Compile the server-side TypeScript (html-renderer.ts + generated file)
execSync('npx tsc', { stdio: 'inherit' });

console.log('Build complete.');
